# Generated by Django 5.0.6 on 2024-05-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
